### ISSUE TITLE
Cryptic error when missing docker images

### ISSUE THREAD

**Issue by bnaul** [mltsp/mltsp#56] opened 2015-08-26 21:57 UTC
Running the custom feature tests without first pulling or building the required docker images gives an error like: `APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal string into Go value of type struct {}")`. Should catch this somewhere higher up and present an error that relates to docker somehow.

**Comment by acrellin** [comment] 2015-08-26 23:57
I'm getting
`APIError: 404 Client Error: Not Found ("No such image: mltsp/base_disco (tag: latest)")`
when trying to run the custom feature tests without the required image.

**Comment by stefanv** [comment] 2015-08-27 00:07
This was due to an invalid usage of the volumes parameter.  Fixed in #57

**Comment by acrellin** [comment] 2015-08-27 00:08
@bnaul, I think this has to do with the changes to the Docker volume mount paths introduced in PR 57 https://github.com/mltsp/mltsp/pull/57/files - though I am unable to reproduce this on my machine when the required container is not present

**Comment by acrellin** [comment] 2015-08-27 00:08
@stefanv, that's what I was thinking, thanks.

**Closed by stefanv** 2015-08-27 00:07 UTC
